# Generated by Django 5.0.6 on 2024-07-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('DocType', models.CharField(choices=[('CPF', 'CPF'), ('NIS', 'NIS')], default='', max_length=3, verbose_name='Tipo de documento')),
                ('NdaFicha', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número da Ficha')),
                ('NIS_CPF', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='NIS ou CPF')),
                ('Nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('Endereço', models.TextField(verbose_name='Endereço')),
                ('Ação', models.CharField(choices=[('Alteração de endereço', 'Alteração de endereço'), ('Atualização cadastral', 'Atualização cadastral'), ('Criação de cadastro', 'Criação de cadastro'), ('Declaração escolar', 'Declaração escolar'), ('Exclusão de pessoa', 'Exclusão de pessoa'), ('Gestão de bloqueio/cancelamento', 'Gestão de bloqueio/cancelamento'), ('Gestão de pessoa', 'Gestão de pessoa'), ('Inclusão de pessoa', 'Inclusão de pessoa'), ('Transferência', 'Transferência')], max_length=50, verbose_name='Ação')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_update', models.DateField(auto_now=True)),
                ('Prioridade', models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], max_length=3, verbose_name='Prioridade')),
                ('Status', models.CharField(choices=[('stts_0', 'A ser atendido'), ('stts_1', 'Em atendimento'), ('stts_2', 'Atendimento encerrado')], max_length=102, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('data', models.DateField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='data')),
                ('pessoas', models.ManyToManyField(related_name='relatorios', to='api.pessoa')),
            ],
        ),
    ]
