# Generated by Django 5.0.6 on 2024-08-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='Ação',
            field=models.CharField(choices=[('Alteração de endereço', 'Alteração de endereço'), ('Atualização cadastral', 'Atualização cadastral'), ('Consulta', 'Consulta'), ('Criação de cadastro', 'Criação de cadastro'), ('Declaração escolar', 'Declaração escolar'), ('Exclusão de pessoa', 'Exclusão de pessoa'), (
                'Gestão de bloqueio/cancelamento', 'Gestão de bloqueio/cancelamento'), ('Gestão de pessoa', 'Gestão de pessoa'), ('Inclusão de pessoa', 'Inclusão de pessoa'), ('Informarção de renda', 'Informarção de renda'), ('Transferência', 'Transferência')], max_length=50, verbose_name='Ação'),
        ),
    ]
