# Generated by Django 5.0.6 on 2025-01-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pessoa_ação'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='benefit_situation',
            field=models.CharField(blank=True, choices=[('Bloqueado', 'Bloqueado'), ('Cancelado', 'Cancelado'), ('Suspenso', 'Suspenso'), ('Liberado', 'Liberado'), ('Não contemplado', 'Não contemplado'), ('Desconhecido', 'Desconhecido')], default='Desconhecido', max_length=15, null=True, verbose_name='benefit_situation'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='isUnderInvestigation',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='isUnderInvestigation'),
        ),
    ]
