# Generated by Django 5.1.5 on 2025-01-15 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_digitador_id_digitador_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitador',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='digitador',
            name='username',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='username'),
        ),
    ]
